alias c='clear'
alias s='neofetch'
alias ra='ranger'
# alias ranger='ranger --choosedir=$HOME/.rangerdir; LASTDIR=`cat $HOME/.rangerdir`; cd "$LASTDIR"'
alias sra='sudo -E ranger'
alias vim='nvim'
alias vi='nvim'
alias nv='nvim'
alias l='ls -la'
alias gc='git clone'
alias lg='lazygit'
# alias pon='export https_proxy=http://127.0.0.1:2340;export http_proxy=http://127.0.0.1:2340;export all_proxy=socks5://127.0.0.1:1080'
# alias poff='export https_proxy=;export all_proxy='
alias pon='expressvpn connect smart'
alias poff='expressvpn disconnect'
alias sbr='sudo vi /sys/class/backlight/intel_backlight/brightness'
alias h='history'
alias p='xsel -ob | xsel -ip'
alias b='xsel -op | xsel -ib'
alias op='xsel -op'
alias ob='xsel -ob'
